# You need to change the setting depneding on your dataset.

###########################################################
#                FEATURE EXTRACTION SETTING               #
###########################################################

sampling_rate: &sampling_rate
    16000
downsample_factors: &downsample_factors
    - 4
    - 4
    - 4
    - 4
upsample_factors: &upsample_factors
    - 4
    - 4
    - 4
    - 4
code_size: &code_size
    16
code_bits: &code_bits
    8
context_window: &context_window
    - 2
    - 2

stft_params: &stft_params
    fft_sizes: [128, 256, 512, 1024]
    hop_sizes: [32, 64, 128, 256]
    win_sizes: [128, 256, 512, 1024]
    window: "hann_window"

###########################################################
#         GENERATOR NETWORK ARCHITECTURE SETTING          #
###########################################################
generator_type: "NWCNet"
generator_params:
    sampling_rate: *sampling_rate
    downsample_factors: *downsample_factors
    upsample_factors: *downsample_factors
    code_size: *code_size
    code_bits: *code_bits
    context_window: *context_window
    encoder_params:
        in_channels: 64
        conv_channels: [32, 64, 128, 256]
        conv_kernel_size: [9, 7, 5, 3]
        conv_dilation: [[1,1,1], [1,1,1], [1,1,1], [1,1,1]]
        conv_groups: [1, 2, 4, 8]
        act_func: "ReLU"
        act_params:
            inplace: false
        act_func_transition: "Tanh"
        act_params_transition: {}
        padding_mode: "same"
        conv_class_name: "_LightConv1d"
    decoder_params:
        embed_size: 1024
        in_channels: 64
        conv_channels: [256, 128, 64, 32]
        conv_kernel_size: [5, 7, 11, 17]
        conv_dilation: [[1,3,5], [1,3,7], [1,3,9], [1,3,9,11]]
        conv_groups: [8, 4, 2, 1]
        act_func: "ReLU"
        act_params:
            inplace: false
        act_func_transition: "PReLU"
        act_params_transition:
            init: 0.142
        padding_mode: "same"
        conv_class_name: "_LightConv1d"
    pqmf_params:
        subbands: 2
        taps: 14
        beta: 8.0
    use_weight_norm: true

###########################################################
#       DISCRIMINATOR NETWORK ARCHITECTURE SETTING        #
###########################################################
discriminator_type: "MultiWaveSTFTDiscriminator"
discriminator_params:
    multi_wave_discriminator_params:
        num_dwt: 4
        kernel_size: 5
        layers: 8
        conv_channels: 64
        use_weight_norm: true
    multi_stft_discriminator_params:
        <<: *stft_params
        num_layers: [4, 5, 6, 7]
        kernel_sizes: [5, 5, 5, 5]
        conv_channels: [64, 64, 64, 64]
        use_weight_norm: false

###########################################################
#                   STFT LOSS SETTING                     #
###########################################################
stft_loss_params:
    <<: *stft_params

###########################################################
#                       LOSS SETTING                      #
###########################################################
lambda_adv: 1.0
lambda_mse: 200.0
lambda_stft: 1.0
lambda_punish: 0.001

###########################################################
#                  DATA LOADER SETTING                    #
###########################################################
batch_size: 16
batch_max_steps: 32000
pin_memory: true
num_workers: 8

###########################################################
#             OPTIMIZER & SCHEDULER SETTING               #
###########################################################

generator_optimizer_type: "AdamW"
generator_optimizer_params:
    lr: 0.0002
    weight_decay: 0.01

generator_scheduler_type: "StepLR"
generator_scheduler_params:
    step_size: 500000
    gamma: 0.5
generator_grad_norm: 10

discriminator_optimizer_type: "RAdam"
discriminator_optimizer_params:
    lr: 0.0001
    eps: 1.0e-6
    weight_decay: 0.0

discriminator_scheduler_type: "StepLR"
discriminator_scheduler_params:
    step_size: 500000
    gamma: 0.5
discriminator_grad_norm: 1

###########################################################
#                    INTERVAL SETTING                     #
###########################################################
discriminator_train_start_steps: 200000
train_max_steps: 1000000
save_interval_steps: 1000
eval_interval_steps: 10000
log_interval_steps: 1000

###########################################################
#                     OTHER SETTING                       #
###########################################################
num_save_intermediate_results: 8

