# You need to change the setting depneding on your dataset.

###########################################################
#                FEATURE EXTRACTION SETTING               #
###########################################################

fft_size: &fft_size
    512
hop_size: &hop_size
    256
downsample_factors: &downsample_factors
    - 2
    - 2
    - 2
    - 2

###########################################################
#         GENERATOR NETWORK ARCHITECTURE SETTING          #
###########################################################
generator_type: "ResRNNUNet"
generator_params:
    fft_size: *fft_size
    hop_size: *hop_size
    downsample_factors: *downsample_factors

###########################################################
#       DISCRIMINATOR NETWORK ARCHITECTURE SETTING        #
###########################################################
discriminator_type: "MultiWaveSTFTDiscriminator"
discriminator_params:
    multi_wave_discriminator_params:
        num_dwt: 5
        kernel_size: 5
        layers: 8
        conv_channels: 64
        use_weight_norm: false
    multi_stft_discriminator_params:
        fft_sizes: [128, 256, 512, 1024, 2048]
        hop_sizes: [32, 64, 128, 256, 512]
        win_sizes: [128, 256, 512, 1024, 2048]
        num_layers: [3, 4, 5, 6, 7]
        kernel_sizes: [5, 5, 5, 5, 5]
        conv_channels: [64, 64, 64, 64, 64]
        use_weight_norm: false

###########################################################
#                       LOSS SETTING                      #
###########################################################
lambda_pcm: 200
lambda_mag: 1
lambda_spec: 1
lambda_adv: 1

###########################################################
#                  DATA LOADER SETTING                    #
###########################################################
batch_size: 8
segment_size: 32512
pin_memory: true
num_workers: 8

###########################################################
#             OPTIMIZER & SCHEDULER SETTING               #
###########################################################

generator_optimizer_type: "AdamW"
generator_optimizer_params:
    lr: 0.001
    betas: [0.8, 0.99]
    eps: 1.0e-9
    weight_decay: 0.01

generator_scheduler_type: "StepLR"
generator_scheduler_params:
    step_size: 100000
    gamma: 0.98
generator_grad_norm: 5

discriminator_optimizer_type: "RAdam"
discriminator_optimizer_params:
    lr: 0.0002
    eps: 1.0e-6
    weight_decay: 0.0

discriminator_scheduler_type: "StepLR"
discriminator_scheduler_params:
    step_size: 500000
    gamma: 0.5
discriminator_grad_norm: 1

###########################################################
#                    INTERVAL SETTING                     #
###########################################################
train_max_steps: 1000000
save_interval_steps: 10000
eval_interval_steps: 1000
log_interval_steps: 1000

###########################################################
#                     OTHER SETTING                       #
###########################################################
num_save_intermediate_results: 8

